security:
  basic:
    enabled: true
  user:
    name: user
    password: password123
server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/mensao/microservice-config-repo
          username:
          password:
