security:
  basic:
    enabled: true
  user:
    name: user
    password: password123
server:
  port: 8761  #Eureka默认的端口
eureka:
  client:
    register-with-eureka: false #registerWithEureka:false 是否要注册到其他 eureka 中，false 即为不注册到其他 eureka 中。不把当前的 Eureka Server 当成一个 Eureka Client 使用。
    fetch-registry: false #fetchRegistry:false 是否要合并别的 eureka 上面的数据。false 为不合并其他 eureka 上面的数据。不把当前的 Eureka Server 当成一个 Eureka Client 使用。
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka  #defaultZone:http://localhost:8761/eureka/ 中的 /eureka/ 不可以省略，因为这是 eureka 通信的地址。Server端也要配置这个参数是因为每个 eureka server 它也是一个 eureka client ，因为在 eureka 集群里面我们要相互注册所以每个 eureka server 也是一个 eureka client ，也都注册到 eureka 服务注册列表中。